apiVersion: v1
kind: Service
metadata:
  name: itdt-frontend-service
  labels:
    app: itdt-frontend
spec:
  selector:
    app: itdt-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
